# Generated by Django 2.2.8 on 2022-03-15 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.CharField(max_length=100,
                 primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=100,
                 primary_key=True, serialize=False, unique=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('deleted', models.BooleanField(default=False)),
                ('airplane', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='device_manager_service_api.Airplane')),
            ],
        ),
    ]
